### PR TITLE
Fixed crash of qdmr on failed decoding of codeplug for DR1801UV (fixed #437)

### LINKED ISSUE #437: Crash of qdmr on failed decoding of codeplug for DR1801UV.
Hi!
I built qdmr-435-implement-manual-device-interface-selection.

In settings I deactivated auto-detect.
Then clicked "download codeplug".

Debug in src/application.cc@1001: Set icon theme to 'light'.
Debug in src/application.cc@81: Search for translation in '/usr/local/share/locale/de_DE/LC_MESSAGES'.
Debug in src/application.cc@81: Search for translation in '/usr/local/share/locale/de/LC_MESSAGES'.
Debug in src/application.cc@84: Installed translator for locale 'de_DE'.
Debug in src/repeaterbookcompleter.cc@328: Loaded repeater cache of 0 entries.
Debug in lib/userdatabase.cc@132: Loaded user database with 259618 entries from /home/pk/.local/share/DM3MAT/qdmr/user.json.
Debug in lib/talkgroupdatabase.cc@140: Loaded talk group database with 1675 entries from /home/pk/.local/share/DM3MAT/qdmr/talkgroups.json.
serialnmea: No known GPS device found. Specify the COM port via QT_NMEA_SERIAL_PORT.
Debug in src/application.cc@137: Last known position: 
Debug in src/application.cc@189: Create main window using icon theme 'light'.
serialnmea: No known GPS device found. Specify the COM port via QT_NMEA_SERIAL_PORT.
qt.positioning.geoclue2: Already stopped
Debug in src/application.cc@554: Last device is invalid, search for new one.
Debug in lib/usbserial.cc@118: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@118: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@157: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/c7000device.cc@236: Search for C7000 devices matching VID:PID 1206:227.
Debug in src/application.cc@558: No save device found, continue searching for unsave ones.
Debug in lib/usbserial.cc@118: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@118: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@157: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/usbserial.cc@118: Search for serial port with matching VID:PID 67b:23a3.
Debug in lib/c7000device.cc@236: Search for C7000 devices matching VID:PID 1206:227.
ERROR in src/application.cc@562: Kein passendes Gerät gefunden.

I see no way to select the tty or to select DR1801UV. Maybe I am looking in the wrong places?
Should I select DR1801UV before pressing download? Or should I be asked after pressing download?
And switching off auto-detection doesnt seem to change anything for me.

I tried two different cables, both with the same result.
Both cables report: idVendor=1a86, idProduct=7523

And I found my second DR1801UV which has a working codeplug installed, no difference.

Maybe the zip-file is not yet updated?
md5sum qdmr-435-implement-manual-device-interface-selection.zip
537806a85dc9b21566ef380c24a8a7c5  qdmr-435-implement-manual-device-interface-selection.zip

Regards,
Patrick

_Originally posted by @DH1PK in https://github.com/hmatuschek/qdmr/issues/435#issuecomment-2112642974_

### PR DESCRIPTION
**Pull request by hmatuschek**

### CODE REVIEW

**Comment by DH1PK** [comment]
Hi!

Maybe I'm doing something wrong?

Downloaded 460.diff to my qdmr-devel folder from yesterday.
git apply 460.diff
make
sudo make install
qdmr



Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).
Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Try to detect radio at Serial interface 'ttyUSB0'.
Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.
Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.
Debug in ***@***.***: Open interface to Auctus A6 based
radio.
Debug in ***@***.***: Send aa06010403bb
ERROR in ***@***.***: Serial port error: (12) Operation timed out.
ERROR in ***@***.***: QSerialPort: Operation timed out
ERROR in ***@***.***: Cannot read response 0h.
ERROR in ***@***.***: Cannot receive response.
ERROR in ***@***.***: Cannot enter programming mode.
ERROR in ***@***.***: Cannot connect to DR-1801UV.
ERROR in ***@***.***: Cannot read codeplug from device:
Interface not in idle state. State=4.
ERROR in ***@***.***: Cannot read codeplug from device.
Debug in ***@***.***: Serial port will close now.

Tried both TRX, same result.

Can I download some branch with this patch applied and recompile everything?

Regards,
Patrick


Am Mo., 22. Juli 2024 um 09:43 Uhr schrieb Hannes Matuschek <
***@***.***>:

**Comment by hmatuschek** [comment]
The pull request it w.r.t. the `master` branch. However, that should not be this problem. But I've also not touched the interface code to the DR1801.

**Comment by hmatuschek** [comment]
I'll merge it into master. Checkout that branch and if there is something wrong with it, simply reopen issue #437.

**Comment by DH1PK** [comment]
Thank you!
Will report later.

Am Mo., 22. Juli 2024 um 11:29 Uhr schrieb Hannes Matuschek <
***@***.***>:

**Comment by DH1PK** [comment]
git clone https://github.com/hmatuschek/qdmr.git
cd qdmr
make
sudo make install
dmr
--> turn on & connect DR1801 UV
--> Button Download
"TTYUSB0" --> OK
"DR1801UV" --> OK

But the TRX Display does NOT indicate communication mode!

Then after a few seconds:

Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Try to detect radio at Serial interface 'ttyUSB0'.
Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.
Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.
Debug in ***@***.***: Open interface to Auctus A6 based
radio.
Debug in ***@***.***: Send aa06010403bb
ERROR in ***@***.***: Serial port error: (12) Operation timed out.
ERROR in ***@***.***: QSerialPort: Operation timed out
ERROR in ***@***.***: Cannot read response 0h.
ERROR in ***@***.***: Cannot receive response.
ERROR in ***@***.***: Cannot enter programming mode.
ERROR in ***@***.***: Cannot connect to DR-1801UV.
ERROR in ***@***.***: Cannot read codeplug from device:
Interface not in idle state. State=4.
ERROR in ***@***.***: Cannot read codeplug from device.
Debug in ***@***.***: Serial port will close now.

Tried both TRX, same result.

Looks identical to "qdmr-devel with applied patch".

Something's broken...

Regards,
Patrick

Am Mo., 22. Juli 2024 um 11:32 Uhr schrieb cologne bynight <
***@***.***>:

**Comment by DH1PK** [comment]
Tried once more:

restarted qdmr, restarted TRX, pressed download and it worked!!!

Debug in ***@***.***: Search for serial ports.
Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).
Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Try to detect radio at Serial interface 'ttyUSB0'.
Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.
Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.
Debug in ***@***.***: Open interface to Auctus A6 based
radio.
Debug in ***@***.***: Send aa06010403bb
Debug in ***@***.***: Got response aa0781040183bb.
Debug in ***@***.***: Send aa06000006bb
Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.
Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,
Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.
Debug in ***@***.***: Set baudrate to 115200.
Debug in ***@***.***: Send aa06010106bb
Debug in ***@***.***: Start reading 122256b of codeplug
memory.
Debug in ***@***.***: Reset baudrate to 9600.
Debug in ***@***.***: Serial port will close now.

--> GUI seems to show the expected data.

Will do some more testing and report later.

(maybe my cable has a problem or - as you said - A6 is "difficult"...)

Thank you very much!
Patrick

Am Mo., 22. Juli 2024 um 12:11 Uhr schrieb cologne bynight <
***@***.***>:

**Comment by DH1PK** [comment]
After successfully reading from my programmed TRX I tried to write to my
"factory new" TRX.

Tried several times with varying results. Sometimes the TRX switches to
"Memory prog..." but sometimes not.
But even after an upload there the TRX showed "Memory prog..." the
programming is not successful:

Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).
Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Try to detect radio at Serial interface 'ttyUSB0'.
Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.
Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.
Debug in ***@***.***: Open interface to Auctus A6 based
radio.
Debug in ***@***.***: Send aa06010403bb
Debug in ***@***.***: Got response aa0781040183bb.
Debug in ***@***.***: Send aa06000006bb
Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.
Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,
Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69eb892e1bb.
Debug in ***@***.***: Set baudrate to 115200.
Debug in ***@***.***: Send aa06010106bb
Debug in ***@***.***: Start reading 122256b of codeplug
memory.
Debug in ***@***.***: Reset baudrate to 9600.
Debug in ***@***.***: Send aa06010403bb
Debug in ***@***.***: Got response aa0781040183bb.
Debug in ***@***.***: Send
aa12010200010001da8c42e90000258049bb
Debug in ***@***.***: Got response aa08810201008abb.
Debug in ***@***.***: Set baudrate to 9600.
Debug in ***@***.***: Write codeplug...
Debug in ***@***.***: Receive write-ACK.
ERROR in ***@***.***: Unexpected start-of-packet byte:
Expected aah, got 0h.
ERROR in ***@***.***: Cannot complete codeplug write.
ERROR in ***@***.***: Cannot finish write operation
properly. Partial write?
ERROR in ***@***.***: Cannot write codeplug to the device.
Debug in ***@***.***: Serial port will close now.
Debug in ***@***.***: Write complete.

Regards,
Patrick



Am Mo., 22. Juli 2024 um 12:15 Uhr schrieb cologne bynight <
***@***.***>:

**Comment by DH1PK** [comment]
After several attempts to write the downloaded codeplug to the new TRX:

Write never succeeds.

Error message is:
ERROR in ***@***.***: Unexpected start-of-packet byte:
Expected aah, got 0h.
ERROR in ***@***.***: Cannot complete codeplug write.
ERROR in ***@***.***: Cannot finish write operation
properly. Partial write?
ERROR in ***@***.***: Cannot write codeplug to the device.

Sometimes the TRX locks up during write, switching off at the rotary knob
then does not work.
After removing and reinstalling the battery the old factory programming is
still active.

Regards,
Patrick

Am Mo., 22. Juli 2024 um 12:36 Uhr schrieb cologne bynight <
***@***.***>:

**Comment by hmatuschek** [comment]
Unplugging the cable from the computer might help. The A6 sends some random
data during boot. This must be cleared before attempting to read/write a
codeplug.

DH1PK ***@***.***> schrieb am Mo., 22. Juli 2024, 13:12:

**Comment by DH1PK** [comment]
Hi!

tried writing after re-plugging USB cable. No success, same error message.
From looking at the progress indicator and looking at the TRX display: TRX
seems to get into "Memory prog..." mode at the start of programming and
then gets out of this mode while qdmr still transfers.

Furthermore I successfully downloaded the codeplug from the "new" TRX,
deleted all channels and zones and added a single analog channel and a
single zone with this one channel.
then tried to upload this minimum zone after re-plugging the cable. No
success.

qdmr seems to download the codeplug before uploading. Maybe this leads to
problems? Could you make qdmr upload without downloading first?

see:

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.
Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.
Debug in ***@***.***: Open interface to Auctus A6 based
radio.
Debug in ***@***.***: Send aa06010403bb
Debug in ***@***.***: Got response aa0781040183bb.
Debug in ***@***.***: Send aa06000006bb
Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.
Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,
Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69eb892e1bb.
Debug in ***@***.***: Set baudrate to 115200.
Debug in ***@***.***: Send aa06010106bb
Debug in ***@***.***: Start reading 122256b of codeplug
memory.
Debug in ***@***.***: Reset baudrate to 9600.
Debug in ***@***.***: Send aa06010403bb
Debug in ***@***.***: Got response aa0781040183bb.
Debug in ***@***.***: Send
aa12010200010001da8cfc25000025803bbb
Debug in ***@***.***: Got response aa08810201008abb.
Debug in ***@***.***: Set baudrate to 9600.
Debug in ***@***.***: Write codeplug...
Debug in ***@***.***: Receive write-ACK.
ERROR in ***@***.***: Unexpected start-of-packet byte:
Expected aah, got 0h.
ERROR in ***@***.***: Cannot complete codeplug write.
ERROR in ***@***.***: Cannot finish write operation
properly. Partial write?
ERROR in ***@***.***: Cannot write codeplug to the device.
Debug in ***@***.***: Serial port will close now.
Debug in ***@***.***: Write complete.

Will try using dmrconf to upload and get back to you...


Am Mo., 22. Juli 2024 um 13:17 Uhr schrieb Hannes Matuschek <
***@***.***>:

**Comment by DH1PK** [comment]
sorry, no luck:

dmrconf -D ttyUSB0 -R DR1801UV write '2024-07-22 DR1801 01.yaml'
Warning in ***@***.***: Verification Issue: Warn: In : The
support for this radio is still under development. Some features may sill
be missing or are not well tested.


Warning in ***@***.***: Verification Issue: Warn: In List
'channels', Element 0 ('PMR  1'): Frequency 446.006MHz is outside of
allowed frequency ranges.
Warning in ***@***.***: Verification Issue: Warn: In List
'channels', Element 0 ('PMR  1'): Frequency 446.006MHz is outside of
allowed frequency ranges.
[==================================================] 100%
ERROR in ***@***.***: Unexpected start-of-packet byte:
Expected aah, got 0h.
ERROR in ***@***.***: Cannot complete codeplug write.


ERROR in ***@***.***: Cannot finish write operation
properly. Partial write?

ERROR in ***@***.***: Cannot write codeplug to the device.


TRX stayed in "Memory prog..." mode during the whole upload process, but no
success.

Regards,
Patrick

Am Mo., 22. Juli 2024 um 14:45 Uhr schrieb cologne bynight <
***@***.***>:

**Comment by DH1PK** [comment]
different cable, same TRX, verbose output, same negative result:

dmrconf -V -D ttyUSB0 -R DR1801UV write '2024-07-22 DR1801 01.yaml'

Debug in ***@***.***: Using format version 0.12.0.
Debug in ***@***.***: Read codeplug from '2024-07-22 DR1801
01.yaml'.

Debug in ***@***.***: Autodetect radios.


Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for serial ports.


Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).


Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Info in ***@***.***: Found 1 device(s):


Info in ***@***.***:   Serial interface 'ttyUSB0'.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Using device ttyUSB0.


Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.

Debug in ***@***.***: Try to detect radio at Serial interface
'ttyUSB0'.

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.


Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.


Debug in ***@***.***: Open interface to Auctus A6 based
radio.

Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send aa06000006bb


Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.

Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,

Warning in ***@***.***: Verification Issue: Warn: In : The
support for this radio is still under development. Some features may sill
be missing or are not well tested.


Warning in ***@***.***: Verification Issue: Warn: In List
'channels', Element 0 ('PMR  1'): Frequency 446.006MHz is outside of
allowed frequency ranges.
Warning in ***@***.***: Verification Issue: Warn: In List
'channels', Element 0 ('PMR  1'): Frequency 446.006MHz is outside of
allowed frequency ranges.
[                                                  ] 0%


Debug in ***@***.***: Start upload to Baofeng DR-1801UV.
Debug in ***@***.***: Send aa0a01000001c200c8bb


Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69eb892e1bb.

Debug in ***@***.***: Set baudrate to 115200.


[                                                  ] 0%
[=========================                         ] 50%
Debug in ***@***.***: Reset baudrate to 9600.


Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send
aa12010200010001da8c42e90000258049bb

Debug in ***@***.***: Got response aa08810201008abb.


[=========================                         ] 50%
[==================================================] 100%
Debug in ***@***.***: Receive write-ACK.


ERROR in ***@***.***: Unexpected start-of-packet byte:
Expected aah, got 0h.

ERROR in ***@***.***: Cannot complete codeplug write.


ERROR in ***@***.***: Cannot finish write operation
properly. Partial write?

ERROR in ***@***.***: Cannot write codeplug to the device.


Debug in ***@***.***: Serial port will close now.


Debug in ***@***.***: Upload completed.



Am Mo., 22. Juli 2024 um 14:51 Uhr schrieb cologne bynight <
***@***.***>:

**Comment by DH1PK** [comment]
No, the codeplug is never written to the device.
I still see the strange chinese initial programming.


Am Mo., 22. Juli 2024 um 14:59 Uhr schrieb Hannes Matuschek <
***@***.***>:

**Pull request merged**
