### PR TITLE
Fixed crash on incomplete read of codeplug DR-1801UV (A6)

### PR DESCRIPTION
**Pull request by hmatuschek**

### CODE REVIEW

**Comment by DH1PK** [comment]
Hi!
I am currently building devel, will try once more and report.

73s,
Patrick DH1PK

Am Sa., 20. Juli 2024 um 12:11 Uhr schrieb Hannes Matuschek <
***@***.***>:

**Comment by hmatuschek** [comment]
Okay, thanks.

**Comment by DH1PK** [comment]
Hi!

GUI download fails in the same way as always:

Debug in ***@***.***: Try to detect radio at Serial interface 'ttyUSB0'.
Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.
Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.
Debug in ***@***.***: Open interface to Auctus A6 based
radio.
Debug in ***@***.***: Send aa06010403bb
Debug in ***@***.***: Got response aa0781040183bb.
Debug in ***@***.***: Send aa06000006bb
Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.
Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,
Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.
Debug in ***@***.***: Set baudrate to 115200.
Debug in ***@***.***: Send aa06010106bb
Debug in ***@***.***: Start reading 122256b of codeplug
memory.
Debug in ***@***.***: Reset baudrate to 9600.
Debug in ***@***.***: Serial port will close now.
ERROR in ***@***.***: Cannot decode invalid channel at
index 0, got promissed 41 valid channels.
ERROR in ***@***.***: Cannot decode channel elements.
ERROR in ***@***.***: Cannot decode elements.
ERROR in ***@***.***: Cannot decode invalid channel at
index 0, got promissed 41 valid channels.
ERROR in ***@***.***: Cannot decode channel elements.
ERROR in ***@***.***: Cannot decode elements.
Speicherzugriffsfehler (Speicherabzug geschrieben)


Reading on the commandline:

***@***.***:~/qdmr/qdmr-devel$ dmrconf read -V -b -R dr1801uv -D ttyUSB0
codeplug-dr1801uv.bin
Debug in ***@***.***: Autodetect radios.
Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.
Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.
Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.
Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.
Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.
Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.
Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.
Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.
Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.
Debug in ***@***.***: Search for serial ports.
Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).
Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.
Info in ***@***.***: Found 1 device(s):
Info in ***@***.***:   Serial interface 'ttyUSB0'.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Using device ttyUSB0.


Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.

Debug in ***@***.***: Try to detect radio at Serial interface
'ttyUSB0'.

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.


Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.


Debug in ***@***.***: Open interface to Auctus A6 based
radio.

Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send aa06000006bb


Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.

Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,

[                                                  ] 0%


Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.

Debug in ***@***.***: Set baudrate to 115200.


[                                                  ] 0%
[==================================================] 100%
Debug in ***@***.***: Reset baudrate to 9600.


Debug in ***@***.***: Serial port will close now.


Debug in ***@***.***: Save codeplug at 'codeplug-dr1801uv.bin'.



--> Reading binary on the commandline succeeds, see attached file.

Trier readind and decoding as yaml on the commandline, that fails:
***@***.***:~/qdmr/qdmr-devel$ dmrconf read -V -y -R dr1801uv -D ttyUSB0
codeplug-dr1801uv.yaml
Debug in ***@***.***: Autodetect radios.
Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for serial ports.


Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).


Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Info in ***@***.***: Found 1 device(s):


Info in ***@***.***:   Serial interface 'ttyUSB0'.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Using device ttyUSB0.


Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.

Debug in ***@***.***: Try to detect radio at Serial interface
'ttyUSB0'.

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.


Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.


Debug in ***@***.***: Open interface to Auctus A6 based
radio.

Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send aa06000006bb


Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.

Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,

[                                                  ] 0%


Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.

Debug in ***@***.***: Set baudrate to 115200.


[                                                  ] 0%
[==================================================] 100%
Debug in ***@***.***: Reset baudrate to 9600.


Debug in ***@***.***: Serial port will close now.


Debug in ***@***.***: Save codeplug at 'codeplug-dr1801uv.yaml'.


ERROR in ***@***.***: Cannot decode invalid channel at
index 0, got promissed 41 valid channels.

ERROR in ***@***.***: Cannot decode channel elements.


ERROR in ***@***.***: Cannot decode elements.


ERROR in ***@***.***: Cannot decode codeplug:   In
dr1801uv_codeplug.cc:3325: Cannot decode elements.

  In dr1801uv_codeplug.cc:3340: Cannot decode channel elements.


  In dr1801uv_codeplug.cc:60: Cannot decode invalid channel at index 0, got
promissed 41 valid channels.    ***@***.***:~/qdmr/qdmr-devel$ dmrconf read -V
-y -R dr1801uv -D ttyUSB0 codeplug-dr1801uv.yaml
Debug in ***@***.***: Autodetect radios.
Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for serial ports.


Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).


Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Info in ***@***.***: Found 1 device(s):


Info in ***@***.***:   Serial interface 'ttyUSB0'.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Using device ttyUSB0.


Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.

Debug in ***@***.***: Try to detect radio at Serial interface
'ttyUSB0'.

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.


Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.


Debug in ***@***.***: Open interface to Auctus A6 based
radio.

Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send aa06000006bb


Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.

Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,

[                                                  ] 0%


Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.

Debug in ***@***.***: Set baudrate to 115200.


[                                                  ] 0%
[==================================================] 100%
Debug in ***@***.***: Reset baudrate to 9600.


Debug in ***@***.***: Serial port will close now.


Debug in ***@***.***: Save codeplug at 'codeplug-dr1801uv.yaml'.


ERROR in ***@***.***: Cannot decode invalid channel at
index 0, got promissed 41 valid channels.

ERROR in ***@***.***: Cannot decode channel elements.


ERROR in ***@***.***: Cannot decode elements.


ERROR in ***@***.***: Cannot decode codeplug:   In
dr1801uv_codeplug.cc:3325: Cannot decode elements.

  In dr1801uv_codeplug.cc:3340: Cannot decode channel elements.


  In dr1801uv_codeplug.cc:60: Cannot decode invalid channel at index 0, got
promissed 41 valid channels.    ***@***.***:~/qdmr/qdmr-devel$ dmrconf read -V
-y -R dr1801uv -D ttyUSB0 codeplug-dr1801uv.yaml
Debug in ***@***.***: Autodetect radios.
Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for serial ports.


Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).


Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Info in ***@***.***: Found 1 device(s):


Info in ***@***.***:   Serial interface 'ttyUSB0'.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Using device ttyUSB0.


Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.

Debug in ***@***.***: Try to detect radio at Serial interface
'ttyUSB0'.

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.


Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.


Debug in ***@***.***: Open interface to Auctus A6 based
radio.

Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send aa06000006bb


Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.

Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,

[                                                  ] 0%


Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.

Debug in ***@***.***: Set baudrate to 115200.


[                                                  ] 0%
[==================================================] 100%
Debug in ***@***.***: Reset baudrate to 9600.


Debug in ***@***.***: Serial port will close now.


Debug in ***@***.***: Save codeplug at 'codeplug-dr1801uv.yaml'.


ERROR in ***@***.***: Cannot decode invalid channel at
index 0, got promissed 41 valid channels.

ERROR in ***@***.***: Cannot decode channel elements.


ERROR in ***@***.***: Cannot decode elements.


ERROR in ***@***.***: Cannot decode codeplug:   In
dr1801uv_codeplug.cc:3325: Cannot decode elements.

  In dr1801uv_codeplug.cc:3340: Cannot decode channel elements.


  In dr1801uv_codeplug.cc:60: Cannot decode invalid channel at index 0, got
promissed 41 valid channels.    ***@***.***:~/qdmr/qdmr-devel$ dmrconf read -V
-y -R dr1801uv -D ttyUSB0 codeplug-dr1801uv.yaml
Debug in ***@***.***: Autodetect radios.
Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for serial ports.


Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).


Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Info in ***@***.***: Found 1 device(s):


Info in ***@***.***:   Serial interface 'ttyUSB0'.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Using device ttyUSB0.


Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.

Debug in ***@***.***: Try to detect radio at Serial interface
'ttyUSB0'.

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.


Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.


Debug in ***@***.***: Open interface to Auctus A6 based
radio.

Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send aa06000006bb


Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.

Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,

[                                                  ] 0%


Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.

Debug in ***@***.***: Set baudrate to 115200.


[                                                  ] 0%
[==================================================] 100%
Debug in ***@***.***: Reset baudrate to 9600.


Debug in ***@***.***: Serial port will close now.


Debug in ***@***.***: Save codeplug at 'codeplug-dr1801uv.yaml'.


ERROR in ***@***.***: Cannot decode invalid channel at
index 0, got promissed 41 valid channels.

ERROR in ***@***.***: Cannot decode channel elements.


ERROR in ***@***.***: Cannot decode elements.


ERROR in ***@***.***: Cannot decode codeplug:   In
dr1801uv_codeplug.cc:3325: Cannot decode elements.

  In dr1801uv_codeplug.cc:3340: Cannot decode channel elements.


  In dr1801uv_codeplug.cc:60: Cannot decode invalid channel at index 0, got
promissed 41 valid channels.    ***@***.***:~/qdmr/qdmr-devel$ dmrconf read -V
-y -R dr1801uv -D ttyUSB0 codeplug-dr1801uv.yaml
Debug in ***@***.***: Autodetect radios.
Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for serial ports.


Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).


Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Info in ***@***.***: Found 1 device(s):


Info in ***@***.***:   Serial interface 'ttyUSB0'.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Using device ttyUSB0.


Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.

Debug in ***@***.***: Try to detect radio at Serial interface
'ttyUSB0'.

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.


Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.


Debug in ***@***.***: Open interface to Auctus A6 based
radio.

Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send aa06000006bb


Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.

Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,

[                                                  ] 0%


Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.

Debug in ***@***.***: Set baudrate to 115200.


[                                                  ] 0%
[==================================================] 100%
Debug in ***@***.***: Reset baudrate to 9600.


Debug in ***@***.***: Serial port will close now.


Debug in ***@***.***: Save codeplug at 'codeplug-dr1801uv.yaml'.


ERROR in ***@***.***: Cannot decode invalid channel at
index 0, got promissed 41 valid channels.

ERROR in ***@***.***: Cannot decode channel elements.


ERROR in ***@***.***: Cannot decode elements.


ERROR in ***@***.***: Cannot decode codeplug:   In
dr1801uv_codeplug.cc:3325: Cannot decode elements.

  In dr1801uv_codeplug.cc:3340: Cannot decode channel elements.


  In dr1801uv_codeplug.cc:60: Cannot decode invalid channel at index 0, got
promissed 41 valid channels.    ***@***.***:~/qdmr/qdmr-devel$ dmrconf read -V
-y -R dr1801uv -D ttyUSB0 codeplug-dr1801uv.yaml
Debug in ***@***.***: Autodetect radios.
Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Debug in ***@***.***: Search for serial port with matching VID:PID
28e9:18a.

Debug in ***@***.***: Search for serial port with matching VID:PID
1fc9:94.

Debug in ***@***.***: Search for HID interfaces matching VID:PID
15a2:73.

Debug in ***@***.***: Search for DFU devices matching VID:PID
483:df11.

Debug in ***@***.***: Search for serial ports.


Debug in ***@***.***: Found ttyUSB0 (USB 1a86:7523).


Debug in ***@***.***: Search for C7000 devices matching VID:PID
1206:227.

Info in ***@***.***: Found 1 device(s):


Info in ***@***.***:   Serial interface 'ttyUSB0'.
Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Using device ttyUSB0.


Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.

Debug in ***@***.***: Try to detect radio at Serial interface
'ttyUSB0'.

Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.


Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.


Debug in ***@***.***: Open interface to Auctus A6 based
radio.

Debug in ***@***.***: Send aa06010403bb


Debug in ***@***.***: Got response aa0781040183bb.


Debug in ***@***.***: Send aa06000006bb


Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.

Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,

[                                                  ] 0%


Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69e34c33cbb.

Debug in ***@***.***: Set baudrate to 115200.


[                                                  ] 0%
[==================================================] 100%
Debug in ***@***.***: Reset baudrate to 9600.


Debug in ***@***.***: Serial port will close now.


Debug in ***@***.***: Save codeplug at 'codeplug-dr1801uv.yaml'.


ERROR in ***@***.***: Cannot decode invalid channel at
index 0, got promissed 41 valid channels.

ERROR in ***@***.***: Cannot decode channel elements.


ERROR in ***@***.***: Cannot decode elements.


ERROR in ***@***.***: Cannot decode codeplug:   In
dr1801uv_codeplug.cc:3325: Cannot decode elements.

  In dr1801uv_codeplug.cc:3340: Cannot decode channel elements.


  In dr1801uv_codeplug.cc:60: Cannot decode invalid channel at index 0, got
promissed 41 valid channels.

Thank you very much for looking into this!

Regards,
Patrick, DH1PK



Am Sa., 20. Juli 2024 um 15:44 Uhr schrieb Hannes Matuschek <
***@***.***>:

**Comment by DH1PK** [comment]
Created a minimum configuration (one analog channel, one zone containing
this channel).
Did y GUI upload to the factory-new DR1801UV.
crashes:

Debug in ***@***.***: Check if serial port ttyUSB0 still exisist
and has VID:PID 1a86:7523.
Debug in ***@***.***: Try to detect radio at Serial interface 'ttyUSB0'.
Debug in ***@***.***: Try to open Serial interface 'ttyUSB0'.
Debug in ***@***.***: Opened serial port ttyUSB0 with 9600baud.
Debug in ***@***.***: Open interface to Auctus A6 based
radio.
Debug in ***@***.***: Send aa06010403bb
Debug in ***@***.***: Got response aa0781040183bb.
Debug in ***@***.***: Send aa06000006bb
Debug in ***@***.***: Got response
aa3a800001202c4246313830312c41362d303030302d585858582c706f727461626c652c3133364d2d3137344d2c3430304d2d3438304d2cfdbb.
Debug in ***@***.***:
 ,BF1801,A6-0000-XXXX,portable,136M-174M,400M-480M,
Debug in ***@***.***: Send aa0a01000001c200c8bb
Debug in ***@***.***: Got response
aa158100010001dd90000000680002e69eb892e1bb.
Debug in ***@***.***: Set baudrate to 115200.
Debug in ***@***.***: Send aa06010106bb
Debug in ***@***.***: Start reading 122256b of codeplug
memory.
Debug in ***@***.***: Reset baudrate to 9600.
Speicherzugriffsfehler (Speicherabzug geschrieben)
***@***.***:~/qdmr/qdmr-devel$ strings ../2024-07-20/Test\ 01.yaml
version: 0.12.0
settings:
  introLine1: ""
  introLine2: ""
  micLevel: 3
  speech: false
  power: High
  squelch: 1
  vox: 0
  tot: 0
radioIDs:
  []
contacts:
  []
groupLists:
  []
channels:
  - analog:
      id: ch1
      name: DB0XO
      rxOnly: false
      admit: Always
      bandwidth: Narrow
      rxFrequency: 439.1 MHz
      txFrequency: 431.5 MHz
      power: !<!default> ""
      timeout: !<!default> ""
      vox: !<!default> ""
      squelch: !<!default> ""
zones:
  - id: zone1
    name: FM Repeater
    A: [ch1]
    B: []
commercial:
  encryptionKeys:
    []
sms:
  format: DMR
  templates:
    []
***@***.***:~/qdmr/qdmr-devel$

Regards,
Patrick

Am Sa., 20. Juli 2024 um 17:18 Uhr schrieb cologne bynight <
***@***.***>:

**Comment by hmatuschek** [comment]
I need that binary. mailto: dm3mat[at]darc[dot]de

I'll test the minimal example. Looks interesting.

**Comment by hmatuschek** [comment]
For the minimal example, try adding a DMR radio ID. The DR1801UV requires a global DMR ID to be configured. I also need that and only forgot to check it.

**Comment by hmatuschek** [comment]
Ok, the encoding issue is a harder problem, I've opened a new issue (#458) for that.

**Pull request merged**
